[ardulinux_base]
platform =
  # renovate: datasource=git-tags depName=ardulinux packageName=https://github.com/l5yth/ardulinux
  git+https://github.com/l5yth/ardulinux.git#v0.2.0
framework = arduino

build_src_filter =
  ${env.build_src_filter}
  -<platform/esp32/>
  -<nimble/>
  -<platform/nrf52/>
  -<platform/stm32wl/>
  -<platform/rp2xx0>
  -<mesh/wifi/>
  -<mesh/http/>
  -<mesh/eth/>
  -<modules/esp32>

lib_deps =
  ${env.lib_deps}
  rweather/Crypto@0.4.0
  adafruit/Adafruit seesaw Library@1.7.9
  electroniccats/CayenneLPP @ 1.6.1
  adafruit/RTClib @ ^2.1.3
  jgromes/RadioLib@7.4.0

build_flags =
  ${arduino_base.build_flags}
  -DARDULINUX_PLATFORM
  -DRADIOLIB_EEPROM_UNSUPPORTED
  -fPIC
  -lpthread
  -lstdc++fs
  -lbluetooth
  -luv
  -std=gnu17
  -std=c++17
